version: '3'

services:
  app:
    container_name: twitter2firefish
    build: .
    restart: unless-stopped
    volumes:
      - ./data.json:/usr/src/app/data.json
      - ./cookies.json:/usr/src/app/cookies.json
